if: branch !~ ^v\d
language: node_js
jobs:
  include:
  - dist: xenial
    node_js: node
    cache:
      directories: ~/.npm
  - os: osx
    osx_image: xcode10.2
    node_js: 10
    cache:
      directories: ~/.npm
    script: node test.js
  - os: windows
    node_js: node
    script: node test.js
    cache:
      directories: /c/Users/travis/AppData/Roaming/npm-cache
